# Generated by Django 5.2.1 on 2025-08-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_post_author_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='contest_images/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
    ]
